name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches: 
      - "*"
  schedule:
    # Daily at 05:47
    - cron: '47 5 * * *'

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.python.name }} ${{ matrix.reactor.name }}
    runs-on: ${{ matrix.os.runs-on }}
    container: ${{ matrix.os.container[matrix.python.docker] }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
            python_platform: linux
            container:
              2.7: docker://python:2.7-buster
              3.5: docker://python:3.5-buster
              3.6: docker://python:3.6-buster
              3.7: docker://python:3.7-buster
              3.8: docker://python:3.8-buster
          - name: Windows
            runs-on: windows-latest
            python_platform: win32
          - name: macOS
            runs-on: macos-latest
            python_platform: darwin
        python:
          - name: CPython 2.7
            tox: py27
            action: 2.7
            docker: 2.7
          - name: CPython 3.5
            tox: py35
            action: 3.5
            docker: 3.5
          - name: CPython 3.6
            tox: py36
            action: 3.6
            docker: 3.6
          - name: CPython 3.7
            tox: py37
            action: 3.7
            docker: 3.7
          - name: CPython 3.8
            tox: py38
            action: 3.8
            docker: 3.8
        reactor:
          - name: default
            tox: default
            dependencies: default
          - name: Qt5
            tox: qt5
            dependencies: qt5
          - name: asyncio
            tox: asyncio
            dependencies: asyncio
        exclude:
          - python:
              tox: py27
            reactor:
              tox: qt5
          - python:
              tox: py27
            reactor:
              tox: asyncio
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python.name }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python.action }}
          architecture: x64
      - name: Install Linux Qt5 dependencies
        if: matrix.os.python_platform == 'linux' && matrix.reactor.dependencies == 'qt5'
        run: |
          apt-get update --yes
          apt-get install --yes libgl1
      - name: Install
        run: |
          pip install tox
      - name: Test
        run: |
          tox -v -e "${{ matrix.python.tox }}-${{ matrix.reactor.tox }}reactor"
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - short: 38
            dotted: 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python.dotted }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python.dotted }}
          architecture: x64
      - name: Install
        run: |
          pip install tox
      - name: Test
        run: |
          tox -v -e linting
  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - test
      - linting
    steps:
      - name: This
        shell: python
        run: |
          import this
