name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches: 
      - "*"

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.python.name }} ${{ matrix.reactor.name }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
          - name: Windows
            runs-on: windows-latest
          - name: macOS
            runs-on: macos-latest
        python:
          - name: CPython 2.7
            tox: py27
            action: 2.7
          - name: CPython 3.5
            tox: py35
            action: 3.5
          - name: CPython 3.6
            tox: py36
            action: 3.6
          - name: CPython 3.7
            tox: py37
            action: 3.7
          - name: CPython 3.8
            tox: py38
            action: 3.8
        reactor:
          - name: default
            tox: default
          - name: Qt5
            tox: qt5
          - name: asyncio
            tox: asyncio
        exclude:
          - python:
              tox: py27
            reactor:
              tox: qt5
          - python:
              tox: py27
            reactor:
              tox: asyncio
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python.name }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python.action }}
          architecture: x64
      - name: Install
        run: |
          pip install tox
      - name: Test
        run: |
          tox -v -e "${{ matrix.python.tox }}-${{ matrix.reactor.tox }}reactor"
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - short: 37
            dotted: 3.7
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python.dotted }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python.dotted }}
          architecture: x64
      - name: Install
        run: |
          pip install tox
      - name: Test
        run: |
          tox -v -e linting
  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - test
      - linting
