name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          - name: CPython 2.7
            tox: py27
            action: 2.7
          - name: CPython 3.5
            tox: py35
            action: 3.5
          - name: CPython 3.6
            tox: py36
            action: 3.6
          - name: CPython 3.7
            tox: py37
            action: 3.7
        reactor:
          - default
          - qt5
          - asyncio
        exclude:
          - python:
              dotted: 2.7
            reactor: qt5
          - python:
              dotted: 2.7
            reactor: asyncio
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python.name }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python.action }}
          architecture: x64
      - name: Install Linux dependencies
        if: matrix.system.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
      - name: Install
        run: |
          pip install tox
      - name: Set TOXENV
        shell: python
        run: |
          import sys

          toxenv = '${{ matrix.python.tox }}-${{ matrix.reactor }}reactor'

          if sys.platform == 'win32':
              toxenv = 'win-' + toxenv

          print('::set-env name=TOXENV::{}'.format(toxenv))
      - name: Test
        run: |
          tox -v -e "${{ env['TOXENV'] }}"
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - short: 37
            dotted: 3.7
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python.dotted }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python.dotted }}
          architecture: x64
      - name: Install
        run: |
          pip install tox
      - name: Test
        run: |
          tox -v -e linting
